[versions]
minSdk = "24"
targetSdk = "36"
compileSdk = "36"

agp = "9.0.1"
android-tools = "32.0.1"
kotlin = "2.3.10"

[libraries]
android-desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.1.5"
android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
android-security-lint = "com.android.security.lint:lint:1.0.4"
android-tools-common = { module = "com.android.tools:common", version.ref = "android-tools" }

androidx-junit = "androidx.test.ext:junit:1.3.0"
androidx-lint-gradle = "androidx.lint:lint-gradle:1.0.0-alpha05"

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }

lint = { module = "com.android.tools.lint:lint", version.ref = "android-tools" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "android-tools" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "android-tools" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "android-tools" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
android-cacheFix = "org.gradle.android.cache-fix:3.0.3"
develocity = "com.gradle.develocity:4.3.2"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-sam = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
kotlin-assignment = { id = "org.jetbrains.kotlin.plugin.assignment", version.ref = "kotlin" }

playground-android-application = { id = "playground.android-application" }
playground-android-library = { id = "playground.android-library" }
playground-android-test = { id = "playground.android-test" }
playground-kotlin-jvm = { id = "playground.kotlin-jvm" }
playground-lint = { id = "playground.lint" }
