[versions]
agp = "9.0.0"
android-tools = "32.0.0"
kotlin = "2.3.10"

[libraries]
androidx-junit = "androidx.test.ext:junit:1.3.0"
junit = "junit:junit:4.13.2"

lint = { module = "com.android.tools.lint:lint", version.ref = "android-tools" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "android-tools" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "android-tools" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "android-tools" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
