[versions]
agp = "9.0.0"

[libraries]
androidx-junit = "androidx.test.ext:junit:1.3.0"
junit = "junit:junit:4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
